language: python
python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - python setup.py develop
 # - pip install .

# command to run tests
script:
  - pytest

notifications:
  email:
    on_success: never
