language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements-dev.txt
# - python setup.py develop

# command to run tests
script:
  - pytest

notifications:
  email:
    on_success: never
