name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: check
      run: |
        python --version
        pip --version
    - name: install
      run: |
        pip install -r requirements-dev.txt
        python setup.py develop
    - name: test
      run: |
        make test-all
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Checking Versions
      run: |
        python3 --version
        pip3 --version
    - name: Installing
      run: |
        pip3 install setuptools
        pwd
        ls -all
        pip3 install -r requirements-dev.txt
        python3 setup.py develop --user
    - name: Testing
      run: |
        make test-all
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: check
      run: |
        python3 --version
        pip3 --version
    - name: install
      run: |
        sudo pip3 install -r requirements-dev.txt
        sudo python3 setup.py develop
    - name: test
      run: |
        make test-all
