name: pre-commit

# On all pull requests + push to masters
on:
  pull_request:
  push:
    branches: [master]

# Step1: Checkout the code
# Step2: Setup python
# Step3: Run precommit based on .pre-commit-config from repo
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
